### ISSUE TITLE
Reformatting not working

### ISSUE THREAD

**Issue by line47** [jchouse/csscomb-atom#29]
I am having trouble getting the plugin to work with the standard settings.
See settings screenshot and GIF of formatting failing. 
I'm using Atom version 1.14.3 for mac.

![atom-css-comb](https://cloud.githubusercontent.com/assets/1449852/23416146/b193c71c-fdaf-11e6-8dbc-009d75f7d6e2.gif)

![screen shot 2017-02-27 at 10 55 09 am](https://cloud.githubusercontent.com/assets/1449852/23416148/b48df7a8-fdaf-11e6-90e0-faa6c59366c3.png)

**Comment by jchouse** [comment]
U right, in this version didn't work, i'll see.

**Comment by line47** [comment]
Thanks! @jchouse 👍

**Comment by jchouse** [comment]
Sorry for the delay, I understand what the problem is, the new version of CSSComb unit has a different concept:


 <object id="scPlayer"  width="1076" height="635" type="application/x-shockwave-flash" data="https://content.screencast.com/users/JCHouse/folders/Jing/media/18578f75-db3a-47a1-93e3-4fbf31b861d0/jingswfplayer.swf" >
 <param name="movie" value="https://content.screencast.com/users/JCHouse/folders/Jing/media/18578f75-db3a-47a1-93e3-4fbf31b861d0/jingswfplayer.swf" />
 <param name="quality" value="high" />
 <param name="bgcolor" value="#FFFFFF" />
 <param name="flashVars" value="thumb=https://content.screencast.com/users/JCHouse/folders/Jing/media/18578f75-db3a-47a1-93e3-4fbf31b861d0/FirstFrame.jpg&containerwidth=1076&containerheight=635&content=https://content.screencast.com/users/JCHouse/folders/Jing/media/18578f75-db3a-47a1-93e3-4fbf31b861d0/00000002.swf&blurover=false" />
 <param name="allowFullScreen" value="true" />
 <param name="scale" value="showall" />
 <param name="allowScriptAccess" value="always" />
 <param name="base" value="https://content.screencast.com/users/JCHouse/folders/Jing/media/18578f75-db3a-47a1-93e3-4fbf31b861d0/" />
 Unable to display content. Adobe Flash is required.
</object>
